CREATE TABLE Suppliers (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    businessName VARCHAR2(255) NOT NULL,
    businessType VARCHAR2(255) NOT NULL,
    contact VARCHAR2(15) NOT NULL,
    address CLOB NOT NULL
);

CREATE TABLE BUYERS (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100),
    EMAIL VARCHAR2(100) UNIQUE,
    PASSWORD VARCHAR2(255),
    ADDRESS VARCHAR2(255),
    CONTACT VARCHAR2(50)
);
CREATE DATABASE urbanfood;

-- Drop tables to avoid conflicts
DROP TABLE Payments CASCADE CONSTRAINTS;    
DROP TABLE Buyers CASCADE CONSTRAINTS;
DROP TABLE Suppliers CASCADE CONSTRAINTS;
DROP TABLE Products CASCADE CONSTRAINTS;
DROP TABLE Orders CASCADE CONSTRAINTS;

CREATE TABLE products (
    product_id NUMBER PRIMARY KEY,
    product_name VARCHAR2(100),
    description VARCHAR2(255),
    image_path VARCHAR2(255),
    category VARCHAR2(50)
);


CREATE TABLE ORDERS (
    ORDER_ID NUMBER PRIMARY KEY,
    EMAIL VARCHAR2(100),
    ORDER_DATE DATE,
    STATUS VARCHAR2(50)
);

CREATE TABLE order_details (
    ID INT GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    OrderID INT NOT NULL,
    ProductID INT NOT NULL,
    Quantity INT NOT NULL,
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON DELETE CASCADE
);
ALTER TABLE order_details ADD CONSTRAINT fk_product FOREIGN KEY (ProductID) 
REFERENCES Products(ProductID) ON DELETE CASCADE;

CREATE TABLE Payments (
    PaymentID INT PRIMARY KEY,
    OrderID INT NOT NULL,
    PaymentDate DATE,
    Amount DECIMAL(10, 2),
    PaymentMethod VARCHAR(50),
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON DELETE CASCADE
);

CREATE TABLE Deliveries (
    DeliveryID INT PRIMARY KEY,
    OrderID INT NOT NULL,
    DeliveryDate DATE,
    DeliveryStatus VARCHAR(50),
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON DELETE CASCADE
);

CREATE TABLE cart (
    ID INT GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    ProductID INT NOT NULL,
    Quantity INT NOT NULL
);
ALTER TABLE cart ADD CONSTRAINT fk_cart_product FOREIGN KEY (ProductID)
REFERENCES Products(ProductID) ON DELETE CASCADE;

INSERT INTO products (product_id, product_name, description, image_path, category)
VALUES (1, 'Fresh Milk', 'Creamy and delicious milk', '../assets/milk.jpg', 'Dairy');

INSERT INTO products (product_id, product_name, description, image_path, category)
VALUES (2, 'Banana Bread', 'Moist and sweet homemade banana bread.', '../assets/banana_bread.jpg', 'Baked Goods');

-- Insert sample buyer
INSERT INTO BUYERS (ID, NAME, EMAIL, PASSWORD, ADDRESS, CONTACT) VALUES
(1, 'John Doe', 'buyer@example.com', 'password123', '123 Main St', '123-456-7890');

-- Insert sample orders
INSERT INTO ORDERS (ORDER_ID, EMAIL, ORDER_DATE, STATUS) VALUES
(1, 'buyer@example.com', SYSDATE, 'Shipped'),
(2, 'buyer@example.com', SYSDATE, 'Delivered');
