CREATE TABLE Suppliers (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    businessName VARCHAR2(255) NOT NULL,
    businessType VARCHAR2(255) NOT NULL,
    contact VARCHAR2(15) NOT NULL,
    address CLOB NOT NULL
);

CREATE TABLE BUYERS (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100),
    EMAIL VARCHAR2(100) UNIQUE,
    PASSWORD VARCHAR2(255),
    ADDRESS VARCHAR2(255),
    CONTACT VARCHAR2(50)
);

-- Drop tables to avoid conflicts
DROP TABLE Payments CASCADE CONSTRAINTS;    
DROP TABLE Buyers CASCADE CONSTRAINTS;
DROP TABLE Suppliers CASCADE CONSTRAINTS;
DROP TABLE Products CASCADE CONSTRAINTS;
DROP TABLE Orders CASCADE CONSTRAINTS;

CREATE TABLE Products (
    ProductID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Category VARCHAR2(50),
    Price NUMBER(10, 2),
    SupplierID NUMBER,
    FOREIGN KEY (SupplierID) REFERENCES Suppliers(SupplierID) ON DELETE SET NULL
);

CREATE TABLE ORDERS (
    ORDER_ID NUMBER PRIMARY KEY,
    EMAIL VARCHAR2(100),
    ORDER_DATE DATE,
    STATUS VARCHAR2(50)
);

CREATE TABLE order_details (
    ID INT GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    OrderID INT NOT NULL,
    ProductID INT NOT NULL,
    Quantity INT NOT NULL,
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON DELETE CASCADE
);
ALTER TABLE order_details ADD CONSTRAINT fk_product FOREIGN KEY (ProductID) 
REFERENCES Products(ProductID) ON DELETE CASCADE;

CREATE TABLE Payments (
    PaymentID INT PRIMARY KEY,
    OrderID INT NOT NULL,
    PaymentDate DATE,
    Amount DECIMAL(10, 2),
    PaymentMethod VARCHAR(50),
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON DELETE CASCADE
);

CREATE TABLE Deliveries (
    DeliveryID INT PRIMARY KEY,
    OrderID INT NOT NULL,
    DeliveryDate DATE,
    DeliveryStatus VARCHAR(50),
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON DELETE CASCADE
);

CREATE TABLE cart (
    ID INT GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    ProductID INT NOT NULL,
    Quantity INT NOT NULL
);
ALTER TABLE cart ADD CONSTRAINT fk_cart_product FOREIGN KEY (ProductID)
REFERENCES Products(ProductID) ON DELETE CASCADE;

CREATE TABLE baked_goods (
    id NUMBER GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    description CLOB,
    image_path VARCHAR2(255)
);

-- Insert sample baked goods
INSERT INTO baked_goods (name, description, image_path) 
VALUES ('Homemade Bread', 'Freshly baked loaves, soft on the inside and perfectly crusty on the outside.', '../assets/bread.jpeg');

INSERT INTO baked_goods (name, description, image_path) 
VALUES ('Muffins', 'Soft and fluffy muffins in various flavors, baked to perfection.', '../assets/muffin.webp');

INSERT INTO baked_goods (name, description, image_path) 
VALUES ('Cookies', 'Delicious homemade cookies, crunchy on the outside and gooey on the inside.', '../assets/cookies.webp');

-- Insert sample buyer
INSERT INTO BUYERS (ID, NAME, EMAIL, PASSWORD, ADDRESS, CONTACT) VALUES
(1, 'John Doe', 'buyer@example.com', 'password123', '123 Main St', '123-456-7890');

-- Insert sample orders
INSERT INTO ORDERS (ORDER_ID, EMAIL, ORDER_DATE, STATUS) VALUES
(1, 'buyer@example.com', SYSDATE, 'Shipped'),
(2, 'buyer@example.com', SYSDATE, 'Delivered');
